// Azerbaijani map UI strings, keyed by the Georgian source text passed to tr().
export const AZ_MAP_STRINGS: Record<string, string> = {
  "ენის შეცვლა": "Dili dəyiş",
  "გეგმა:": "Plan:",
  "1 წელი": "1 il",
  "3 თვე": "3 ay",
  "1 თვე": "1 ay",
  "სტატუსი:": "Status:",
  "აქტიური": "Aktiv",
  "ძალაშია:": "Etibarlıdır:",
  "ავტომატური განახლება: ჩართულია": "Avtomatik yenilənmə: aktiv",
  "შემდეგი გადახდა:": "Növbəti ödəniş:",
  "ავტომატური განახლება გაუქმებულია.": "Avtomatik yenilənmə ləğv edilib.",
  "თქვენი გამოწერა აქტიური დარჩება": "Abunəliyiniz aktiv qalacaq:",
  "-მდე.": "tarixinədək.",
  "ავტომატური განახლება ამ განახლებაზე არ არის ჩართული.": "Bu ödəniş üçün avtomatik yenilənmə aktiv deyil.",
  "3-თვიანი პერიოდის დასრულების შემდეგ შეგიძლიათ გამოწერა განაახლოთ სრული 3-თვიანი": "3 aylıq müddət bitdikdən sonra abunəliyi tam 3 aylıq",
  "ფასით.": "qiymətlə yeniləyə bilərsiniz.",
  "ავტომატური განახლება: გამორთულია": "Avtomatik yenilənmə: deaktiv",
  "მაგისტრალების არიდება": "Magistrallardan qaç",
  "გრუნტის გზების არიდება": "Torpaq yollardan qaç",
  "მარშრუტის არჩევანი": "Marşrut seçimi",
  "უსწრაფესი": "Ən sürətli",
  "ალტერნატიული": "Alternativ",
  "⚠ რთული გზა": "⚠ Çətin yol",
  "წთ": "dəq",
  "ახლომახლო დამტენი ვერ მოიძებნა. სცადეთ უფრო მოკლე მონაკვეთი.": "Yaxınlıqda doldurma stansiyası tapılmadı. Daha qısa hissəni sınayın.",
  "დამატებულია": "Əlavə edildi",
  "დამტენი ვერ მოიძებნა": "Doldurma stansiyası tapılmadı",
  "ბატარეა · სავალი მანძილი": "Batareya · Yürüş məsafəsi",
  "მარშრუტი": "Marşrut",
  "კმ-ია — საჭიროა დამუხტვის გაჩერება.": "km-dir — doldurma dayanacağı lazımdır.",
  "კმ-ია — არსებული მუხტი საკმარისია.": "km-dir — mövcud yük kifayətdir.",
  "დამტენი იძებნება…": "Doldurma stansiyası axtarılır…",
  "დამუხტვის გაჩერების დამატება": "Doldurma dayanacağı əlavə et",
  "შედეგი ვერ მოიძებნა": "Nəticə tapılmadı",
  "ძიება დროებით მიუწვდომელია. ხელახლა სცადეთ.": "Axtarış müvəqqəti əlçatan deyil. Yenidən cəhd edin.",
  "ადგილი ვერ გაიხსნა. აირჩიეთ სხვა შედეგი.": "Yer açılmadı. Başqa nəticə seçin.",
  "მოძებნეთ ქუჩა, ადგილი ან მისამართი": "Küçə, yer və ya ünvan axtarın",
  "გასუფთავება": "Təmizlə",
  "გამოტოვების ჩასმა": "Boşluq daxil et",
  "გამოტოვება": "Boşluq",
  "იძებნება…": "Axtarılır…",
  "შემდეგი ნაბიჯები": "Növbəti addımlar",
  "ადგილები": "Yerlər",
  "დასრულება": "Bitir",
  "მიმდინარე ადგილის შენახვა": "Cari yeri yadda saxla",
  "სახლი": "Ev",
  "სამსახური": "İş",
  "რჩეულები": "Seçilmişlər",
  "რჩეულებიდან წაშლა": "Seçilmişlərdən sil",
  "ბოლო ადგილები": "Son yerlər",
  "რჩეულებში შენახვა": "Seçilmişlərdə saxla",
  "რჩეულებში დამატება": "Seçilmişlərə əlavə et",
  "-ის დაყენება": "— təyin et",
  "არ არის დაყენებული": "təyin edilməyib",
  "მდებარეობის სიზუსტის შესახებ": "Məkan dəqiqliyi haqqında",
  "Tesla-ს ბრაუზერში GPS-ის სიზუსტე შეიძლება განსხვავდებოდეს.": "Tesla brauzerində GPS dəqiqliyi fərqli ola bilər.",
  "ზოგი firmware მდებარეობას ქსელით ადგენს, რაც ზუსტი ნავიგაციისთვის საკმარისი არ არის.": "Bəzi proqram versiyaları məkanı şəbəkə ilə təyin edir, bu isə dəqiq naviqasiya üçün kifayət deyil.",
  "აპი:": "Tətbiq:",
  "ითხოვს მაღალი სიზუსტის მდებარეობას,": "yüksək dəqiqlikli məkan tələb edir,",
  "მუდმივად აახლებს მას და აჩვენებს სიზუსტის ხარისხს.": "onu daim yeniləyir və dəqiqlik səviyyəsini göstərir.",
  "შეზღუდვა:": "Məhdudiyyət:",
  "ბრაუზერს მანქანის GPS ჩიპზე პირდაპირი": "brauzerin avtomobilin GPS çipinə birbaşa",
  "წვდომა არ აქვს. თუ მანქანის მდებარეობა არაზუსტია, დააკავშირეთ ტელეფონი.": "çıxışı yoxdur. Avtomobilin məkanı dəqiq deyilsə, telefonu qoşun.",
  "საუკეთესო შედეგი:": "Ən yaxşı nəticə:",
  "დაკავშირებული ტელეფონის GPS": "qoşulmuş telefonun GPS-i",
  "მანქანის ეკრანს უფრო ზუსტ მდებარეობას აწვდის.": "avtomobil ekranına daha dəqiq məkan ötürür.",
  "უკუსვლის შემდეგ:": "Geri hərəkətdən sonra:",
  "Tesla ბრაუზერს დროებით აჩერებს.": "Tesla brauzeri müvəqqəti dayandırır.",
  "ბრაუზერის ხელახლა გახსნისას აქტიური მარშრუტი ავტომატურად გაგრძელდება.": "Brauzer yenidən açılanda aktiv marşrut avtomatik davam edəcək.",
  "სთ": "saat",
  "მისვლის დრო": "Çatma vaxtı",
  "დარჩენილი": "Qalıb",
  "დრო": "Vaxt",
  "სიჩქარე": "Sürət",
  "ცენტრში": "Mərkəzlə",
  "ხმის ჩართვა": "Səsi aç",
  "დადუმება": "Səsi bağla",
  "გზის დასრულება": "Marşrutu bitir",
  "მდებარეობა ჩართულია": "Məkan aktivdir",
  "GPS სიგნალი იძებნება…": "GPS siqnalı axtarılır…",
  "მდებარეობა დაბლოკილია — ჩართეთ ბრაუზერის პარამეტრებში": "Məkan bloklanıb — brauzer ayarlarında icazə verin",
  "მდებარეობა მიუწვდომელია — ხელახლა სცადეთ": "Məkan əlçatan deyil — yenidən cəhd edin",
  "მდებარეობის ჩართვა": "Məkanı aktiv et",
  "რუკის ჩატვირთვას ჩვეულებრივზე მეტი დრო სჭირდება. შეამოწმეთ მანქანის ინტერნეტი და ხელახლა სცადეთ.": "Xəritənin yüklənməsi adi haldan uzun çəkir. Avtomobilin internetini yoxlayın və yenidən cəhd edin.",
  "გაჩერება": "Dayanacaq",
  "დანიშნულების ადგილი": "Təyinat yeri",
  "არჩეული ადგილი": "Seçilmiş yer",
  "რუკა იტვირთება…": "Xəritə yüklənir…",
  "რუკა ვერ ჩაიტვირთა": "Xəritə yüklənmədi",
  "ხელახლა ცდა": "Yenidən cəhd et",
  "მარშრუტი ახლდება…": "Marşrut yenilənir…",
  "სუსტი GPS სიგნალი": "Zəif GPS siqnalı",
  "ჩემს მდებარეობაზე დაბრუნება": "Mənim məkanıma qayıt",
  "ჩემი მდებარეობა": "Mənim məkanım",
  "რუკის მოახლოება": "Yaxınlaşdır",
  "რუკის დაშორება": "Uzaqlaşdır",
  "შემდეგი": "Növbəti",
  "წთ ·": "dəq ·",
  "კმ დარჩა · მიხვალთ": "km qalıb · çatırsınız",
  "საწვავი": "Yanacaq",
  "დამუხტვა": "Doldurma",
  "საკვები": "Yemək",
  "ყავა": "Qəhvə",
  "პარკინგი": "Parkinq",
  "ველოდებით მდებარეობას": "Məkan gözlənilir",
  "ძიება ვერ შესრულდა": "Axtarış alınmadı",
  "ახლომახლო იძებნება…": "Yaxınlıqda axtarılır…",
  "ტელეფონით მართვა": "Telefonla idarəetmə",
  "ტელეფონი გაითიშა": "Telefon ayrıldı",
  "მართეთ ეკრანი ტელეფონით": "Ekranı telefonla idarə edin",
  "კოდი იქმნება…": "Kod yaradılır…",
  "ამ ეკრანის მართვა": "Bu ekranı idarə et",
  "ტელეფონის დაკავშირება": "Telefonu qoş",
  "QR კოდი": "QR kod",
  "მოწყობილობის დაკავშირება": "Cihazı qoş",
  "გათიშვა": "Ayır",
  "სპიდომეტრი": "Spidometr",
  "დახურვა": "Bağla",
  "მარშრუტი იტვირთება…": "Marşrut yüklənir…",
  "მარშრუტი ჯერ არ არის": "Hələ marşrut yoxdur",
  "მარშრუტს აცდით — ახლდება…": "Marşrutdan çıxdınız — yenilənir…",
  "მარშრუტი ითვლება…": "Marşrut hesablanır…",
  "კმ ·": "km ·",
  "-მდე": "qədər",
  " · შენახული მარშრუტი": " · saxlanmış marşrut",
  "მდებარეობის სიზუსტე": "Məkan dəqiqliyi",
  "განედი": "En dairəsi",
  "გრძედი": "Uzunluq dairəsi",
  "სიზუსტე": "Dəqiqlik",
  "მ": "m",
  "ასაკი": "Yaş",
  "წმ": "san",
  " · საცდელი მონაცემი": " · test məlumatı",
  " · დაკავშირებული ტელეფონის GPS": " · qoşulmuş telefonun GPS-i",
  "გამოუყენებელი": "Yararsız",
  "სიზუსტე უცნობია": "Dəqiqlik məlum deyil",
  "დაგვიანებული": "Gecikmiş",
  "სავარაუდოდ IP-ით განსაზღვრული მდებარეობაა": "Ehtimal ki, IP ilə təyin edilmiş məkandır",
  "სუსტი": "Zəif",
  "მოხვევების ნავიგაციისთვის არასაკმარისია": "Dönüş-dönüş naviqasiya üçün kifayət deyil",
  "მისაღები": "Qəbul ediləndir",
  "ზოგადი მარშრუტისთვის საკმარისია": "Ümumi marşrut üçün kifayətdir",
  "კარგი": "Yaxşı",
  "ნავიგაციისთვის ზუსტი მდებარეობაა": "Naviqasiya üçün dəqiq məkandır",
  "არ არის დაკავშირებული": "Qoşulmayıb",
  "დაკავშირების კოდი იქმნება…": "Qoşulma kodu yaradılır…",
  "ველოდებით ტელეფონს…": "Telefon gözlənilir…",
  "ტელეფონი დაკავშირებულია": "Telefon qoşulub",
  "ხელახლა ვუკავშირდებით…": "Yenidən qoşulur…",
  "გათიშულია": "Ayrılıb",
  "ტელეფონთან კავშირი გაწყდა": "Telefonla əlaqə kəsildi",
  "კავშირის შეცდომა": "Bağlantı xətası",
  "ტელეფონი გაითიშა — ნავიგაცია მანქანის GPS-ით გრძელდება.": "Telefon ayrıldı — naviqasiya avtomobilin GPS-i ilə davam edir.",
  "ტელეფონთან კავშირი გაწყდა — ნავიგაცია მანქანის GPS-ით გრძელდება.": "Telefonla əlaqə kəsildi — naviqasiya avtomobilin GPS-i ilə davam edir.",
  "მარშრუტი ვერ მოიძებნა": "Marşrut tapılmadı",
  "მარშრუტის სერვისი დატვირთულია — მალე ხელახლა ვცდით.": "Marşrut xidməti məşğuldur — tezliklə yenidən cəhd edəcəyik.",
  "შენახული": "Saxlanmış",
  "ველოდებით მდებარეობას Tesla-ს ბრაუზერიდან ან დაკავშირებული ტელეფონიდან.": "Tesla brauzerindən və ya qoşulmuş telefondan məkan gözlənilir.",
  "იტვირთება…": "Yüklənir…",
  "მონიშნული ადგილი": "İşarələnmiş yer",
  "ტელეფონიდან": "Telefondan",
  "TMap · საქართველო": "TMap · Azərbaycan",
  "ბრაუზერული ნავიგაცია": "Brauzer naviqasiyası",
  "გამოსვლა": "Çıxış",
  "პანელის დამალვა": "Paneli gizlət",
  "ინტერნეტი არ არის — გამოიყენება შენახული მარშრუტი": "İnternet yoxdur — saxlanmış marşrut istifadə olunur",
  "მდებარეობას შემოწმება სჭირდება": "Məkanın yoxlanması lazımdır",
  "თუ მოძრაობისას Tesla-ს ბრაუზერი აღარ განახლდება, დააკავშირეთ ტელეფონი ზემოთ.": "Hərəkət zamanı Tesla brauzeri yenilənmirsə, yuxarıda telefonu qoşun.",
  "პანელის ჩვენება": "Paneli göstər",
  "პანელი": "Panel",
  "გამოიყენეთ ტელეფონი დისტანციური მართვისთვის": "Uzaqdan idarə üçün telefondan istifadə edin",
  "კმ დაშორებით": "km uzaqlıqda",
  "გაუქმება": "Ləğv et",
  "ტრაფიკი ჩართულია": "Tıxac aktivdir",
  "ტრაფიკი გამორთულია": "Tıxac deaktivdir",
  "3D ან 2D რუკის არჩევა": "3D və ya 2D xəritə seçimi",
  "3D და 2D ხედებს შორის გადართვა": "3D və 2D görünüş arasında keçid",
  "ამ ეკრანზე 3D ხედი არ არის მხარდაჭერილი": "Bu ekranda 3D görünüş dəstəklənmir",
  "მუქი რუკის გადართვა": "Tünd xəritəyə keçid",
  "დღისა და ღამის ფერებს შორის გადართვა": "Gündüz və gecə rəngləri arasında keçid",
  "ღამე": "Gecə",
  "დღე": "Gündüz",
  "ენის შეცვლა: სომხური": "Dili dəyiş",
  "რუკა სომხურად": "Xəritənin dili",
  "გაგრძელდა გზა:": "Marşrut davam etdi:",
};
