/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PhoneCodeRouteImport } from './routes/phone.$code'

const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneCodeRoute = PhoneCodeRouteImport.update({
  id: '/phone/$code',
  path: '/phone/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/drive': typeof DriveRoute
  '/phone/$code': typeof PhoneCodeRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/drive': typeof DriveRoute
  '/phone/$code': typeof PhoneCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/drive': typeof DriveRoute
  '/phone/$code': typeof PhoneCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth' | '/drive' | '/phone/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/drive' | '/phone/$code'
  id: '__root__' | '/auth' | '/drive' | '/phone/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  DriveRoute: typeof DriveRoute
  PhoneCodeRoute: typeof PhoneCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/$code': {
      id: '/phone/$code'
      path: '/phone/$code'
      fullPath: '/phone/$code'
      preLoaderRoute: typeof PhoneCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  DriveRoute: DriveRoute,
  PhoneCodeRoute: PhoneCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
