/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhoneCodeRouteImport } from './routes/phone.$code'

const PhoneCodeRoute = PhoneCodeRouteImport.update({
  id: '/phone/$code',
  path: '/phone/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/phone/$code': typeof PhoneCodeRoute
}
export interface FileRoutesByTo {
  '/phone/$code': typeof PhoneCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/phone/$code': typeof PhoneCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/phone/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/phone/$code'
  id: '__root__' | '/phone/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PhoneCodeRoute: typeof PhoneCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/phone/$code': {
      id: '/phone/$code'
      path: '/phone/$code'
      fullPath: '/phone/$code'
      preLoaderRoute: typeof PhoneCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PhoneCodeRoute: PhoneCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
